apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: helloworld-imagestream
  namespace: multi-cloud
spec:
  lookupPolicy:
    local: false
  tags:
  - name: "development"
    from:
      kind: DockerImage
      name: "registry.gitlab.com/gitlab-com/alliances/ibm-red-hat/sandbox/customer-k/multi-cloud-demo/development"
    referencePolicy:
      type: Local
  - name: "production"
    from:
      kind: DockerImage
      name: "registry.gitlab.com/gitlab-com/alliances/ibm-red-hat/sandbox/customer-k/multi-cloud-demo/main"
    referencePolicy:
      type: Local
