apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: helloworld-imagestream
  namespace: multi-cloud
spec:
  lookupPolicy:
    local: true
  importPolicy: 
    scheduled: true
  tags:
  - name: "development"
    importPolicy: {scheduled: true}
    from:
      kind: DockerImage
      name: "registry.gitlab.com/gitlab-com/alliances/ibm-red-hat/sandbox/customer-k/multi-cloud-demo/development:latest"
    referencePolicy:
      type: Source
  - name: "production"
    from:
      kind: DockerImage
      name: "registry.gitlab.com/gitlab-com/alliances/ibm-red-hat/sandbox/customer-k/multi-cloud-demo/main:latest"
    referencePolicy:
      type: Source
