apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-oidc
  namespace: multi-cloud
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.AC Identity Management and Access Control, PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.AC-4 Access Control, PR.IP-1 Baseline Configuration
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-oidc-prod-idm
        spec:
          remediationAction: enforce
          severity: low
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                stringData:
                  user: testing
                kind: Secret
                metadata:
                  name: azure-oauth-secret
                  namespace: multi-cloud 
            - complianceType: musthave
              objectDefinition:
                apiVersion: config.openshift.io/v1
                kind: OAuth
                metadata:
                  annotations:
                    include.release.openshift.io/ibm-cloud-managed: 'true'
                    include.release.openshift.io/self-managed-high-availability: 'true'
                    include.release.openshift.io/single-node-developer: 'true'
                    release.openshift.io/create-only: 'true'
                  name: cluster
                  uid: 6073e6e0-af57-48c2-b3c7-e936fb995cc1
                spec:
                  identityProviders:
                    - mappingMethod: claim
                      name: azure 
                      openID:
                        claims:
                          email:
                            - email
                          name:
                            - name
                          preferredUsername:
                            - preferred_username
                        clientID: 1bb397ff-fbb4-4d25-ad42-22823fa83b23
                        clientSecret:
                          name: azure-oauth-secret
                        extraScopes: []
                        issuer: 'https://login.microsoftonline.com/25efc611-dd49-492c-95bf-8c3410935a90'
                      type: OpenID
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-oidc
  namespace: multi-cloud
placementRef:
  name: placement-policy-oidc
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: policy-oidc
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-oidc
  namespace: multi-cloud
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: cloud
        operator: In
        values:
          - Amazon
