---
apiVersion: v1
kind: Namespace
metadata:
  name: gitlab-auth
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: gitlab-secrets
  namespace: multi-cloud
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - gitlab-secrets
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: gitlab-secrets
  namespace: multi-cloud
spec:
  type: Namespace
  pathname: gitlab-auth
  sourceNamespaces:
    - gitlab-auth
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  annotations:
    secretname: gitlab-secrets
  name: gitlab-secrets-placement
  namespace: multi-cloud
spec:
  clusterSelector:
    matchLabels:
      'usage': 'gitlab'
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: gitlab-secrets
  namespace: multi-cloud
  labels:
    app: gitlab-secrets
spec:
  channel: multi-cloud/gitlab-secrets
  packageFilter:
    annotations:
      secretname: gitlab-secret
  placement:
    placementRef:
      kind: PlacementRule
      name: gitlab-secrets-placement
