---
apiVersion: v1
kind: Namespace
metadata:
  name: gitlab-auth
---
apiVersion: v1
kind: Namespace
metadata:
  name: gitlab-secrets
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: gitlab-secrets
  namespace: gitlab-secrets
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - gitlab-secrets
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: gitlab-secrets
  namespace: gitlab-auth
spec:
  type: Namespace
  pathname: gitlab-secrets
  sourceNamespaces:
    - gitlab-auth
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  annotations:
    secretname: gitlab-secrets
  name: gitlab-secrets-placement
  namespace: gitlab-secrets
spec:
  clusterSelector:
    matchLabels:
      'usage': 'gitlab'
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: gitlab-secrets
  namespace: gitlab-secrets
  labels:
    app: gitlab-secrets
spec:
  channel: gitlab-auth/gitlab-secrets
  packageFilter:
    annotations:
      secretname: gitlab-secret
  placement:
    placementRef:
      kind: PlacementRule
      name: gitlab-secrets-placement
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-secret
  namespace: gitlab-auth
  annotations: 
    apps.open-cluster-management.io/deployables: "secret"
    secretname: gitlab-secret
type: Opaque
stringData:
  secret: Z2l0bGFiLXNlY3JldC12YWx1ZQo=
